### ISSUE TITLE
targetcli may fail to start since eecb633 "Display a more meaningful error when targetcli cannot change dbroot"

### ISSUE THREAD

**Issue by cvubrugier** [open-iscsi/rtslib-fb#105]
At revision eecb633, I added some code to display a more meaningful error when rtslib cannot change the "dbroot" value. This error can be raised when the new "dbroot" value points to a directory that does not exist.

However, there is at least another situation where the "dbroot" value cannot be changed: when the target drivers are already loaded:

    # dmesg
    db_root: cannot be changed: target drivers registered

This second situation should not prevent targetcli from starting.

**Comment by stmcginnis** [comment]
Is there a plan for a new release for this?

Current 2.1.64 release does not include this fix and is causing failure on Fedora for the Cinder project. I currently have a patch up to blacklist back to an earlier version, but would rather be able to bump up our required version to include this change.

**Comment by agrover** [comment]
Yes, let's do some new releases very soon.

**Comment by cvubrugier** [comment]
Fixed by commit [Raise an error about failing to change the dbroot value only if the directory does not exist](../commit/7b879d4c578ec50cf0a2596e2583846c7b397f52).
