### ISSUE TITLE
Regression in 2.1.74 release causing read-only SCSI Block device attachments to fail

### ISSUE THREAD

**Issue by ssudhakarp** [open-iscsi/rtslib-fb#170]
The commit, 964520037320534512713e58bf70be6c428097dc("Fix EPERM errors with scsi_generic devices") added O_RDWR flag to os_open() call in is_dev_in_use() function. This change was introduced to support sg devices. But, this change broke the ability to attach a read-only block device because O_RDWR flag will always result in open() system call to fail for read-only block devices.

**Comment by ssudhakarp** [comment]
Link to the change that caused regression: https://github.com/open-iscsi/rtslib-fb/commit/964520037320534512713e58bf70be6c428097dc#diff-3f39696e74baffb1a3bb597e9485a75f7c67df7502e49ed34d90f0d9e382f4ca

Link to the original issue that introduced the regression: https://github.com/open-iscsi/targetcli-fb/issues/158

**Comment by maurizio-lombardi** [comment]
Thanks for reporting this, I am reviewing the fix you submitted
