### ISSUE TITLE
dpkg: error processing python-rtslib-fb (--install): SyntaxError

### ISSUE THREAD

**Issue by arthurlogilab** [open-iscsi/rtslib-fb#51]
After a `make deb` and doing a `dpkg -i dist/*.deb` I get : 

```
Setting up python-rtslib-fb (2.1.fb49) ...
SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/dist-packages/rtslib/fabric.py', 120, 36, 'version_attributes = {"lio_version", "version"}\n'))

dpkg: error processing python-rtslib-fb (--install):
 subprocess installed post-installation script returned error exit status 101
Setting up python-rtslib-fb-docs (2.1.fb49) ...
Errors were encountered while processing:
 python-rtslib-fb
```

**Comment by cvubrugier** [comment]
This issue is no longer relevant because `make deb` has been removed since commit [Remove build scripts for RPM and Debian packages](../commit/b3f692f60bc933dce0c8c727d9028003014eeddb). Moreover rtslib-fb is packaged in [Debian](https://tracker.debian.org/pkg/python-rtslib-fb). Closing the issue.
