### ISSUE TITLE
RPM, Deb scripts missing from all -fb repos.

### ISSUE THREAD

**Issue by aarcane** [open-iscsi/rtslib-fb#83]
I read one of the commit logs...  and blaming debian for removing a functional, working feature is just low.  Bring it back.  Many of us use it when we're installing from source.  You can easily omit it from the release tarballs if you want for debian's pleasure, but anybody working from the repo probably wants and needs those rpm/apt bits.

**Comment by agrover** [comment]
I feel like I don't have a good understanding of who was using these scripts. Wouldn't distro users who wanted to use a more recent version of -fb pkgs be best served by starting from their distro's packaging scripts, rather than these generic ones? As a developer, I never used the packaging, I just use PYTHONPATH to point to the in-development source trees. It seems like you're an example of a use case we didn't consider, so I'd like to know more.

**Comment by aarcane** [comment]
So distro packages tend to have a lot of issues.  There are often proprietary patches that will add complexities, especially around the startup and shutdown of these utilities.  Not only that, but many of them are built around large scale build systems, and don't make package building simple for someone like me who usually only works with about five different packages rather than thousands.  (I tend to count rtslib, configshell, and targetcli as one 'package' since they pretty much only go together)

**Comment by agrover** [comment]
I feel like if they're in the repo, it's something ultimately I'm responsible for. And they break and need testing (on all possible distro versions??) and so on. So I'd rather not bring them back.

If you wanted to extract them all into a separate repo that we could point to for people who needed this, that would really be my preferred solution. I could also see some possible usability improvements from integrating the pkgbuild process for the three into a single procedure.

What do you think? Other options?

**Comment by aarcane** [comment]
I don't have the packaging knowhow to maintain them, nor do I really track this project enough to know what changes are made and need applying to the packaging scripts.  What's cool about the deb and rpm packages is that if they build on one platform they'll build on any compatible platform.

That said, I did have to change the dependency information in the template..  but I was able to do this because the packaging exists in-repo.  If somebody wanted to make a separate package repo that had the packaging information and makefile and everything, but just referencing the -fb repos as a submodule, that would be a great compromise.

I like your idea of merging the three projects into one project, since they're used pretty much only and exclusively together.  I'm honestly not sure why they're even separate anymore.

**Comment by rickysarraf** [comment]
The debian/ and RPM packaging was rotting in here. And not just here, but many other projects too. Many distributions have different policies and priorities, and do packaging accordingly.

For users installing from source, should follow installing from source, as is usually done. You could ease that with tools like stow, that were built for this very purpose.

Asking upstream to maintain packaging is useless. Why limit it to Fedora and Debian only ? Add a Gentoo ebuild, and also an Arch equivalent. And also take care of openSUSE differences for the RPM packaging.

Please don't add distro packaging unless you intend to maintain it. Take VirtualBox as an example. They have the resources to maintain/ship VirtualBox in .deb format. But still we get lots of useless bug reports about their packaging, in our bug tracker.

**Comment by rickysarraf** [comment]
@aarcane What do you mean by "proprietary patches adding complexities" ?

**Comment by aarcane** [comment]
Let's see, as an example, the stock targetcli-fb init and targetcli save all their configuration in a single file, and manage to save and reload it on startup and shutdown without losing changed.  If, however, I use the stock suse packaging, suse splits the configuration across two distinct *sets* of configuration files each having half of the configuration interleaved between them.  It's nigh on impossible to save your configuration, it's kinda cobbled together so that if, for example, a backstore fails to load, and you fix that and restart your server, you lose *every* WWN, because when it shuts down it loses those configurations, and it's more than a dozen files total.  making them immutable breaks the shutdown and restart process with the suse patched-in init scripts.

That's not the worst.  I switched away from debian because their targetcli packages were just untenable.  It's been long enough I don't recall the details, so I won't try to give specifics, but it was a complete disaster.

The .deb and .rpm packaging sources in this repo work and work beautifully.  As for your alleged "differences", they amount to changing the name of one dependency.  Most future changes should also be tantamount to adding and removing dependencies.    And who better to update two already perfectly working rpm/deb source files with new dependencies, than the people who are in fact controlling what those dependencies are.  

finally, to quote you..  
> users installing from source, should follow installing from source, as is usually done.
The usual method is TERRIBLE, and users end up having to use something like checkinstall which means more work and less long-term maintainability.  As a user, I'm greatful to find more and more packages maintaining a package default build script, because that means when distros flub up their packages, which is all too often the case, we have a clean, pure, official, "as the creators intended" package we can fall back on, with at most, simple minor tweaks to, for example, change dependency names.

That is literally the extend of debian packaging differences between debian and ubuntu and mint is changed dependency names, and also the extent of the differences between fedora and centos and suse.  So long as you choose to use a dependency name here that is discernable, it's trivial for a moderately informed user of your software to say "Oh, hey, let's adjust this".  

You make it sound like maintaining these package scripts is a major task.  But it's not.  All it requires is that when you add a new dependency or majorly change a file location, you update the build files as well.  A task that's trivial for someone who's aware of such changes as they happen to handle making in an existing build script, but a monumental task for an outsider to take on.

As for gentoo and arch, I certainly wouldn't suggest *adding* them unless there's some demand for them or somebody contributes them.  However, if they're contributed, the changes remain equally trivial.  Update your dependencies.  Everything is good.

You're seriously making a mountain out of a molehill to justify robbing users of this molehill and heap the mountain down in it's place.

**Comment by rickysarraf** [comment]
There is more to maintaining a package in a distribution than just shipping it in a format understandable by the package manager. But it seems like that is the perception that is built these days. The reason why distribution packages are favored over foreign ones, has more to do with their tight integration with the rest of the distribution and comprehensive testing.

Every distribution has certain release goals, and all packages adhere to those. For upstream projects, maintaining their own packaging for distributions, would mean to track each distribution and each of their release.

Take Mergerfs as an example: https://github.com/trapexit/mergerfs/releases

I am not of the opinion that packaging should be done here, but if Andy or anyone else is willing to maintain it, that is fine.

**Comment by aarcane** [comment]
And while in some instances, a tight integration with the rest of the distribution is desirable, targetcli and the entire lio stack is one situation where nobody has managed to get package management correct *except* the upstream developers.  The packages built by the source materials here are top notch compared to any distribution package stack I've yet encountered, both being up to date and functioning properly without unexpected or unintended side-effects.  Every distribution *optimized* package for every distro I've run has been buggy and an awful experience compared to the in-tree package sources.  Removing them is a downright travesty, and if you want to insist on perpetrating travesties, I won't stop you..  But I'm hoping since I can't appeal to your rational side, I can appeal to your emotional side.  Don't be the villains that do this.  LIO is already failing to gain market share because distribution packages suck.  Don't make it worse by removing the only actually viable option.

**Comment by agrover** [comment]
Surely Fedora packages are flawless 😃 😄 😄 

But seriously, I don't want 'em back. The best alternative I can see is a separate repo, and we point to them in the README.mds. If you won't set it up then I guess I will.

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Tue, 2016-11-22 at 15:38 -0800, Christ Schlacta wrote:
> And while in some instances, a tight integration with the rest of the
> distribution is desirable, targetcli and the entire lio stack is one situation
> where nobody has managed to get package management correct except the upstream
> developers. The packages built by the source materials here are top notch
> compared to any distribution package stack I've yet encountered, both being up
> to date and functioning properly without unexpected or unintended side-
> effects. Every distribution optimized package for every distro I've run has
> been buggy and an awful experience compared to the in-tree package sources.
> Removing them is a downright travesty, and if you want to insist on
> perpetrating travesties, I won't stop you.. But I'm hoping since I can't
> appeal to your rational side, I can appeal to your emotional side. Don't be
> the villains that do this. LIO is already failing to gain market share because
> distribution packages suck. Don't make it worse by removing the only actually
> viable option.

I don't want to comment about your experiences with particular distributions.
But, for Debian, the previous packages were in decent shape. And recently,
Christope and Christian did an awesome job of getting -fb packages in shape,
which is what will now become part of the next Debian Stable (Stretch).


- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlg1eSAACgkQpjpYo/Lh
dWluBA//d9ec2znii/fNs2Ldbu6fpOTbtoyM+JgLCSw9soKG8/ZvULpQqlwF57JA
d4yHsH1VyIpELHI9fs4jHdgtfQ/90opwGgSkjvnXVM2xiHaFSuxp5hR7PkQluZZx
l5cMJKqqKAKAc/0oAo2NKiNuRgca4Relxm5h8Y280L/6u1Q4I3bwLsPFOz8BAWz+
J6x4CJCPrHq/9KatN1K3aqP9uNTF+xk4U0Ja1+HHwZ3CsFjnmROp+AEm4swUMiGA
sd+hk2aUY9FkHTHLgy49vmMsYTYY6LQY2Xu2wp88K4mU7rTp8CZLn7lM98dvY9f3
4Uwyl/BOnAUdUKFTs4J4n4U0AE/CQzTKmjIQVLzwRmsrSKcmSQeZS7J/pKBpVMBD
pYMB8TMK+0H8Sj3a8MidNM9wlRvaj+BGEigflnFzqlxfduFs8MGjPrjss0SAp+5W
P31GfgAnJ791k+UWZMIqGCGHKLacqEwqlBOMEI3iWrl41wZcnizPoH1OnVqUNXGW
rzZ7YJU8tS6VsnG3/iaosP0c5RQehQuRTffsRl6umCudrixv0049WIod2TnaPNof
L6nOiRiEBnWC3hzC7tXnYpM668w1TvAUQzCutXshcHtNaHSAUKRUH6bGUF4UArCw
29c/9DPjo+lZW5CGvemf6IGtPuAeehC6OVA3mNFluwebcLmmROQ=
=e0Gf
-----END PGP SIGNATURE-----

**Comment by agrover** [comment]
I've pulled the scripts out into their own repo, https://github.com/open-iscsi/targetcli-pkgscripts , in a very blunt manner. There is further work needed adjusting paths & improving integration between the three components' build scripts, but it's a start.
